name = "asset-tokenization-microservice"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "asset-tokenization-microservice-prod"

[env.staging]
name = "asset-tokenization-microservice-staging"

# R2 bucket for document storage
[[r2_buckets]]
binding = "R2"
bucket_name = "asset-tokenization-docs"

# D1 database for primary data
[[d1_databases]]
binding = "DB"
database_name = "asset-tokenization-db"
database_id = "your-database-id"

# KV for caching and sessions
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

# Environment variables
[vars]
NODE_ENV = "production"
API_VERSION = "v1"

# Secrets (set via wrangler secret put)
# JWT_SECRET
# API_KEY
# DATABASE_URL (if using external database)
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
